language: rust
sudo: false

cache:
  - cargo

rust:
  - nightly

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
  - cargo install-update -a

script:
  - cargo check && cargo check --release
  # exclude the examples from the test build, just the lib
  - cargo test --lib && cargo test --lib --release
  - cd book && mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  keep-history: true
  name: DocsBot
  verbose: true
  on:
    branch: master
