[package]
name = "gba"
description = "A crate (and book) for making GBA games with Rust."
version = "0.3.0-pre"
authors = ["Lokathor <zefria@gmail.com>", "Thomas Winwood <twwinwood@gmail.com>"]
repository = "https://github.com/rust-console/gba"
readme = "README.md"
keywords = ["gba"]
edition = "2018"
license = "Apache-2.0"

publish = false

[dependencies]
typenum = "1.10"
gba-proc-macro = "0.2.1"

#[dev-dependencies]
#quickcheck="0.7"
# TODO: F

[profile.release]
lto = true
panic = "abort"
