[package]
name = "gba"
description = "A crate for 'raw' style GBA development. If you want a 'managed' experience, try the `agb` crate instead."
repository = "https://github.com/rust-console/gba"
version = "0.7.4"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
bitfrob = "0.2.3"
voladdress = "1.0.2"

[profile.dev]
opt-level = 3

[package.metadata.docs.rs]
# The crate can only be built for targets that have thumb-interworking support,
# because otherwise the instruction_set attribute can't be used.
targets = ["armv5te-unknown-linux-gnueabi"]
